spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: testuser
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

